# Generated by Django 4.2.13 on 2024-06-24 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_notes_table_table_notes_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'time_slot']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['capacity']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_table',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '<country code><local number>'. Up to 15 digits allowed, with an optional leading '+'.", regex='^\\+?[1-9]\\d{0,3}\\d{4,14}$')]),
        ),
    ]
