# Generated by Django 4.2.13 on 2024-06-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options_alter_table_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.table'),
        ),
    ]
