# Generated by Django 4.2.13 on 2024-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_table_options_alter_booking_booked_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '09:30 - 11:00'), (2, '11:30 - 13:00'), (3, '13:30 - 15:00'), (4, '15:30 - 17:00'), (5, '17:30 - 19:00'), (6, '19:30 - 21:00')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(choices=[(1, '1-2 people'), (2, '3-4 people'), (3, '5-6 people'), (4, '7-8 people')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
