# Generated by Django 4.2.13 on 2024-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_time_slot_alter_table_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
    ]
