# Generated by Django 4.2.13 on 2024-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_staff_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(choices=[(2, '1 guest'), (2, '2 guests'), (4, '3 guests'), (4, '4 guests'), (6, '5 guests'), (6, '6 guests')]),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
    ]
