# Generated by Django 4.2.13 on 2024-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_no_of_guests_alter_table_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(choices=[(1, '1 guest'), (2, '2 guests'), (3, '3 guests'), (4, '4 guests'), (5, '5 guests'), (6, '6 guests')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '09:00 - 10:45'), (2, '11:00 - 12:45'), (3, '13:00 - 14:45'), (4, '15:00 - 16:45'), (5, '17:00 - 18:45'), (6, '19:00 - 20:45')]),
        ),
    ]
